### ISSUE TITLE
Colormap for Scatter Plot Z Values

### ISSUE THREAD

**Issue by drgrib** [gonum/plot#345] opened 2017-04-14 20:30 UTC
It would be ideal to have the ability to add Z values to scatter plot using the `HeatMap` color palettes like this
http://stackoverflow.com/a/6065493/130427

**Comment by btracey** [comment] 2017-04-14 23:06
This is a duplicate of https://github.com/gonum/plot/issues/195, right?

**Comment by drgrib** [comment] 2017-04-14 23:37
Aha. Yes, looks like it. Thanks. Not sure how to mark it as duplicate / referenced so feel free to do so. Thanks.

**Closed** 2017-04-15 01:59 UTC
