### ISSUE TITLE
Creating a heatmap with 0 depth (min value == max value) causes panic

### ISSUE THREAD

**Issue by jasonpfox** [gonum/plot#302] opened 2016-07-18 17:22 UTC
Converting depth / Z range into colorbar scaling generates a divide by 0 NaN.

While 0 depth / flat heatmaps are not themselves meaningful, generating heatmaps on provided data sets can see cases where all values in the map are identically equal...

**Comment by kortschak** [comment] 2016-07-19 00:55
It seems to me that it is the responsibility of the user to check that there is a meaningful range on their data.

Maybe we could panic in the case that the range is zero.

**Comment by btracey** [comment] 2016-07-19 12:08
It's not an unreasonable request to plot flat data. It can happen reasonably often, especially when automatically generating plots from code generated with floating point data. It seems better to define a small range around the value and plot anyway.

**Comment by kortschak** [comment] 2016-07-19 12:22
That opens up a whole heap of questions that I don't think have answers. The main one is what does it actually mean to render a field of a single colour (or multiple fields of a single colour - or worse multiple fields where some a single colours and don't correspond between each other or the panels that do have meaningful data on them).

Nowhere else in gonum do we do sloppy things like this, I really don't see why we should do it here.

**Comment by ctessum** [comment] 2016-07-19 14:30
An additional problem is, if whole plot is made to be a single color in this case, which color should be chosen? I don't think there's a universally correct answer.

What if it returns an error instead of panicking? It seems like that would be more appropriate because it is a user-level issue rather than a problem with the code. Then, if a user wants to handle this case in a specific way, they can just catch the error and act appropriately.

For example:

``` go 
NewHeatMap(g GridXYZ, p palette.Palette) (*HeatMap, error) {
  ...
  if min == max {
    return nil, fmt.Errorf("error message")
  }
}
```

**Comment by kortschak** [comment] 2016-07-19 22:36
It is not an error to create a Heatmap with a zero range, just to use one in a plot - there may be subsequent code to modify ranges. If the error is just a warning, that's a new use of errors for us that would be surprising. Unfortunately errors in plotting are not yet handled without panics (this has been discussed before and I believe is an open issue), so that is the option if we want to handle this explicitly.

**Comment by jasonpfox** [comment] 2016-07-20 19:51
It could be meaningful to either select minimum, maximum, or mid-range palette value for 0 depth data, as long as it is documented. and consistent.  As a user who occasionally sees flat floating point data generated from data sets (generally observing a series of images), generating a plot with uniform color would be much preferable to error out in someway.  One other possible fix would be to ensure that h.max is at least epsilon above h.min when creating the plot.   A flat plot with uniform color is still meaningful in this case and easy to generate, so it does not make sense to not return that just because we don't want to and force the user to deal with error handling where they generally would not need to, especially since the only plot error handling currently is panics as mentioned above.

I could write a wrapper around heatmap plot to enforce some min bounds but it seems like it makes more sense to push this error checking into the package itself instead of requiring end-user wrappers...

**Comment by kortschak** [comment] 2016-07-21 03:57
>It could be meaningful to either select minimum, maximum, or mid-range palette value for 0 depth data

And this is where the problem lies.

>As a user who occasionally sees flat floating point data generated from data sets (generally observing a series of images)

I think this outcome is very much the least frequent that I could imagine. The problem is that to optimise for this use case we elide error checking for the far more common use case in which a zero width range is an error that would not be found without visual inspection of the plot output.

Your case is covered by 3 additional lines of code (2 semantic) with arbitrary optimisation to your specific use.

```
h := plotter.NewHeatmap(data, pal)
if h.Min = h.Max {
    h.Max = math.Nextafter(h.Max, math.Inf(1))
}
```

The alternative is either plots that due to other errors are meaningless (say the data was not written and so the plot input is all zero) or an optimisation that is not the right one for that particular case.

I agree that the panic is not correct since it's a runtime panic rather than a plotter package panic, and there is little meaningful context by the time the panic happens. Both of those can be fixed by careful error management - using a panic with a plotter package error and probably having the error type hold the plot.Plotter that caused the panic. Papering over the problem is not the right answer though.

**Comment by jasonpfox** [comment] 2016-08-02 15:48
One other thought a few weeks ... maybe your 
`if h.Min = h.Max {
    h.Max = math.Nextafter(h.Max, math.Inf(1))
}`
Should go in NewHeatMap for cases where input is not a minMaxer and heatmap is auto-generating its own scale.  My issue really came form NewHeatMap auto-genrating its own scale that then caused panic in the rendering potion of the code when I didn't touch the min and max values in-between.

I still say that If I don't touch the min and max values, then whatever comes out of NewHeatmap should just work downstream without further errors or panics.  If I was the one who was over-riding or setting those Min and Max values then allowing a panic would make somewhat more sense to me (but I still would not be a fan).  Any error here fi we wanted one should probably come from the NewHeatmap area when 0 range is seen???

**Comment by kortschak** [comment] 2016-08-02 21:18
I can understand your position, but I really don't think it is the right thing to do. Essentially, for the sake of convenience we trade away safety.

Is there a reason you can't check the plot range. This is why Min and Max are exposed.

@eaburns what is your view here?

**Comment by btracey** [comment] 2016-08-02 22:02
````
Nowhere else in gonum do we do sloppy things like this, I really don't see why we should do it here.
````

If you make a plot with one data point, the x and y axes are given some arbitrary window (https://play.golang.org/p/_3WvbxLyld). Why should heatmaps be any different? It seems like they're basically the same problem and so should have similar behavior.

**Comment by kortschak** [comment] 2016-08-02 22:11
I agree that they are similar, however they are different enough for different behavior to be warranted. I really don't understand why it's not possible to just write a `func myHeatMap` that calls NewHeatMap and sets Min and Max appropriately. It's the extra lines. Further is the range is expanded by default it is not possible to easily wire the Chinese function that safely handles bad data.

**Comment by eaburns** [comment] 2016-08-02 23:40
I thought about it. Here's my summary:

To me, this is exactly the same problem of `Axis.Min==Axis.Max`, it's just a 3rd axis. Currently, x and y axes solve this problem by calling `Axis.sanitizeRange`, which in this case will do `Min--` and `Max++` to make the range non-empty. I think we should do that.

# Longer version

I see four ways forward:
1. Do the same thing that we do for x and y axes: `Min--; Max++`.
2. Panic in HeatMap — @kortschak's suggestion
3. Change the API of all `Plot` methods so that they can return errors.
4. Change the API of HeatMap so that we can return an error if the range of the z-axis is zero *before* `HeatMap.Plot`. Here's one option:
```
// Unexport Min and Max so that they cannot be changed after the HeatMap is created.

func NewHeatMap(g GridXYZ, p palette.Palette) *HeatMap {
  h, err := NewHeatMapMinMax(g, p, minMax(g))
  if err != nil {
    panic("impossible")
  }
  return h
}

func NewHeatMapMinMax(g GridXYZ, p pallet.Pallet, min, max float64) (*HeatMap, error) {
  if min == max { // or some more float64-friendly equality comparison
    return nil, errors.New("min==max")
  }
 …
}
```

Personally, I don't like options 2 or 3. Option 2 is easy, but it seems strange to take one stance on the x and y axes, but a different on the z axis of HeatMaps. Option 3 seems too difficult because it adds a lot of boilerplate code, propogating errors through lots of places just to hanndle a single case with HeatMaps.

Option 3 is OK. It makes the min/max of HeatMap look a bit less like the min/max of x and y axes, because the user no longer has the option to change their values without the library reserving the ability to return an error regarding their choice of values.

However, Option 1 seems best to me. This is just another axis. Why treat it differently from the two axes that we already have? (Separately, we can debate whether the current min=max handling for axes was a good idea. I can see arguments why it's not: Why add 1 unit of padding on both sides? Why not 0.5, making the resulting range a unit? etc.)

**Comment by eaburns** [comment] 2016-08-02 23:49
For the record, I don't mind panicking in a case like this. However if we panic here, we have to panic there too.

**Comment by ctessum** [comment] 2016-08-03 00:01
To extend option 1, if the colormap is separated from the HeatMap as proposed in #304, the min and max values could be replaced with an [axis](https://godoc.org/github.com/gonum/plot#Axis) object. Benefits of this would be that:

- behavior as related to this issue would be exactly the same as it is in the x and y axes
- as in the x and y axes, different normalizers could be used for log scale etc
- it would make it easier to make color legends 
- The range of the colormap axis could be extended by adding plotters to it, as is done for the x and by axes

**Comment by kortschak** [comment] 2016-08-03 00:06
The reason that I take such a strong stance on this is that the behaviour that exists at the moment (preferably improved with better data tracing) has found bugs for me in the past that would be silently passed with the proposed sanitisation behaviour.

Fundamentally, the difference between the two axis cases is that there is vastly more data on a heatmap than on a line plot (particularly in the case where there is only a single point on that line plot).

Addressing each point in turn.

1. This facilitates silent passing of buggy code. As stated above, it is just another axis, but in this case size really does matter.

2. Obviously my preference - with improvements.

3. I don't mind either way with this one. There are other cases where erroring during a plot may be valuable.

4. This does not help the case that, from what I understand, provoked the original issue - the use of multipanel heat maps. If the user cannot see the min and max values that cannot conform them to a global range. The user may not know the actual range to be rendered over until immediately prior to the rendering of the plot. This leaves us where we are now - we should either panic or error at the plot rendering stage.

**Comment by eaburns** [comment] 2016-08-03 15:56
Can you give an example of the bug? Do you mean that you were computing the data incorrectly such that you only got a single z value across all points? What if someone else makes a similar mistake with a line plot and only gets a single y value? Should we panic?

Can you elaborate on the size argument? I don't think I understand it. Why is it easy to spot this error when there are 10 data points but not when there are 1,000,000?

As for 4, (and I don't really prefer this option, but I want to clarify) the caller clearly has access to the data, since they pass it to the New function. Why can't they compute the min/max but we can?

**Comment by jasonpfox** [comment] 2016-08-03 17:49
I like the proposals.  Fundamentally, I don't see or treat a 0 range heatmap as any more of an error than 0 length X or Y axis and agree that they should be handled the same.  I have never come across plotting support in another language or tools that would fail to plot just because the data didn't have depth or range to it.

Only thing to be careful of if I am reading coorectly is that Min-- and Min++ should increment by min floating point vice 1.0 (may be what was intended above), as the Z /depth range of meaningful heatmaps can often be along lines of 1e-4 to 2e-4 or similar ranges.

**Comment by kortschak** [comment] 2016-08-03 21:54
>Can you give an example of the bug?

Analysing bins of genomic data for size distributed objects is the use case. The number of heat map elements as large (~3000x100s). I had two separate issues, one where I had not correctly written the data and they were zeroes. This is barely distinguishable from a field of zero with a single element different. A panic pointed me straight to the cause.

>What if someone else makes a similar mistake with a line plot and only gets a single y value? Should we panic?

No, we shouldn't panic. It is easy to see from a plot like this that something is wrong.

>Can you elaborate on the size argument? I don't think I understand it. Why is it easy to spot this error when there are 10 data points but not when there are 1,000,000?

I don't really know how to answer this. If you see a single circle (or none) in the centre of a scatter plot and you were expecting a multitude, you immediately know something went wrong. If you have a field of one colour with 1,000,000 points and you were expecting a field of colour with 1,000,000 and possibly <0.01% of them to be different, you may not.

>As for 4, (and I don't really prefer this option, but I want to clarify) the caller clearly has access to the data, since they pass it to the New function. Why can't they compute the min/max but we can?

The Heatmap already knows. Why do the work again? I really don't understand why it needs to be unexported unless to achieve something like @ctessum is proposing in #304. Unless we are getting benefits from use in an interface all it does is reduce utility.

**Comment by kortschak** [comment] 2016-08-03 22:13
>Fundamentally, I don't see or treat a 0 range heatmap as any more of an error than 0 length X or Y axis and agree that they should be handled the same.

n matters.

>I have never come across plotting support in another language or tools that would fail to plot just because the data didn't have depth or range to it.

It won't fail to plot if the possible error conditions have been considered and properly handled.

I have still not had an answer from anyone why writing a `myHeatmap` function to perform the range adjustment as described above is so difficult. If the ranges are expected to be zero width then presumably the author of the code is writing tests to handle this (and I am worried about the analysis that they are doing); if they are part of a panel ensemble with some panels with zero width, then a function `adjustRanges(h ...plotter.Heatmap) error` obviates the problem safely and more easily under the current approach than some of the proposals while retaining the capacity to catch input bugs.

The function should only ever panic once for any particular user (perhaps this could be reduced to zero by documentation and reading).

>Only thing to be careful of if I am reading coorectly is that Min-- and Min++ should increment by min floating point vice 1.0 (may be what was intended above), as the Z /depth range of meaningful heatmaps can often be along lines of 1e-4 to 2e-4 or similar ranges.

At the point that you have decided to mutate the range, what difference does this make. You have a zero real range with a median point and you expand it to a finite range with a median point. The median is the same. The fact that you are arguing for particular range to be adopted tells me in spades that this choice should be made by the programmer, not the library; there is no universally meaningful default for an infinite scaling of a range.

**Comment by kortschak** [comment] 2016-08-03 22:16
>To extend option 1, if the colormap is separated from the HeatMap as proposed in #304, the min and max values could be replaced with an axis object. Benefits of this would be that:

While I'm interested in seeing the outcomes of #304 from an API perspective, I think it would be wrong to conflate a colour scale axis with the `plot.Axis` type. They are conceptually similar in that they are axes, but the implementation details are dissimilar enough to warrant distinct types if this is adopted.

**Comment by eaburns** [comment] 2016-08-03 23:42
I'm still not convinced that HeatMap is any more special than Axis. Yes, if you expected >1 scatter points and only saw 1 then it's clear that there is a bug. Likewise, if you expected a heat map with two very distinct colors and only saw a single color, it's clear that there is a bug. This was not your problem. You expected the differences in the data to be visually indistinguishable. In that case, I agree, it's hard to tell if the data was different or if there was a bug making all values the same. However, I don't see why this is specific to either HeatMap or large data sets. If I have a line with 3 points — a small data set indeed — that I expect to appear visiually horizontal, then I have the same problem: I can't tell from simply looking at the plot if they are horizontal, due to some bug, or only *nearly* horizontal.

But I don't think that we should argue any further. I don't think that this particular point truly warrants it. I also think that you understand my argument but don't find it convincing — my saying more won't help that. That's fair.

Either way we choose, panic or not panic, there is a very easy solution for the other. If we panic, as you have said numerous times, it's very easy to simply check whether Min==Max and then fix it. If we don't panic, it's very easy to check whether Min==Max, or whatever other invariants you expect of your data, and fix it.

**Comment by kortschak** [comment] 2016-08-03 23:52
Final points.

>However, I don't see why this is specific to either HeatMap or large data sets. If I have a line with 3 points — a small data set indeed — that I expect to appear visiually horizontal, then I have the same problem: I can't tell from simply looking at the plot if they are horizontal, due to some bug, or only nearly horizontal.

The difference here is that it is a reasonable use for a heat map to find few points out of many to visually search for features. If you are relying on a scatter to determine whether beta is 0 or small then you are doing it wrong.

>If we panic, as you have said numerous times, it's very easy to simply check whether Min==Max and then fix it. If we don't panic, it's very easy to check whether Min==Max, or whatever other invariants you expect of your data, and fix it.

The difference here is that a check for |min-max| == 0 is simple and the user can choose the appropriate range to replace it with. The alternative is to know that |min-max| == defaultValue and then iterate over the data again to find what the value actually was and then error/panic.

**Comment by jasonpfox** [comment] 2016-08-16 12:36
My last $0.02,  It sounds like you are trying to use an error condition from a heatmap Panic to find other bugs in your code.  It would seem like if a 0 depth heapmap is an error condition _in your case_, then that would be where the 1-3 lines (if min==max catch anr report your error) would make a lot of sense.

For those cases where min==max is _not_ an error condition, such as mine particular use, there should not be a need to check and adjust for a non-error condition.  The concept of forcing or allowing panic to uncover errors outside of the plot package in some code cases and introducing unneeded panics in others.  As I said above, allowing panic would be OK, as long as the automatic min-max found in heatmap createion never caused this.  As a design policy?

If I get a new heatmap, with no problems or errors reported, then turn around and ask to plot that heatmap, then there should be no panic in plot. 

If you really want a panic here then I believe it should come at the time of creation, or a refusal to return a heatmap from creation that would cause plot to Panic.

I am workign around this in my code, but it really feels like we are allowinb / forcing a Panic to help some peoples troubleshooting and complicating others code as well.

Fundamentally, a heatmap with 0 depth is not any kind of heatmap or plot error, nor shoudl it be, any more than plotting an XY scatter with all X points equal, or a histogram with no data and universally 0 bins, ....

On another aside, someone let me know if there is general interest in me workign to adapt my colorbar approach into a more generally usable option for heatmaps.

**Comment by btracey** [comment] 2017-05-11 04:46
In case there's any way this is open for discussion, I just encountered this in a real project. I had a list of lists, and then was checking pairwise if they were statistically different. I did this for many cases, and my code panicked in the middle of the run because in one of the cases none of them were statistically different (so the field is all 0). It's surprising to me (having forgotten this issue), that heatmap should panic in this case.

**Comment by kortschak** [comment] 2017-05-11 05:11
TBH, I think that is telling you something, but what would you propose?

@eaburns Is there any reason not to change the `Plotter` interface to `Plot(draw.Canvas, *Plot) error` and the signature of `*Plot.Draw` to `Draw(c draw.Canvas) error`? [Here](https://github.com/gonum/plot/issues/302#issuecomment-233787482) I wrote "Unfortunately errors in plotting are not yet handled without panics (this has been discussed before and I believe is an open issue), so that is the option if we want to handle this explicitly", but I don't recall where that discussion is.

**Comment by btracey** [comment] 2017-05-11 05:17
I don't understand ... what is it telling me? The data I want to plot is actually all 0s, which is a boring plot on its own, but useful when compared with other heatmaps on different lists of lists.

**Comment by kortschak** [comment] 2017-05-11 06:09
My issue is that a single heatmap which is flat (possibly at zero) does not know that it is part of a larger ensemble. If it is made aware of that by being placed in a grid then probably it wants to have its value included in the collective range, or omitted with a label in its place stating that it was uniform.

I just had a look at what R and plotly do in this situation. R does not render and of the tiles and emits what is essentially a warning that the range is invalid. plotly renders grey, but does not issue a warning. Though I can't see a builtin for rendering heatmaps with octave/matlab, the approach I have seen renders things that are unknown or undefined as zero (I don't like this). At the moment, we have an overflow and an underflow colour. We could add another (this seems awful), or use one of them (this seems incorrect) or we could interpolate between them and render that (this has a almost sickening appeal) - by default this third option would render the heatmap as blank.

**Comment by ctessum** [comment] 2017-05-11 06:31
What I would propose would be for Heatmap to take a different data type as input, something like:

``` go
type ColorGrid interface {
  Dim func() (int, int)
  X0, Y0 func() float64
  Dx, Dy func() int
  Color(x, y int) color.Color
}
```
That would leave choosing colors as an exercise for the user. There could be a default that mapped scalar values to colors using a palette.ColorMap, which I believe panics if the range is 0.

**Comment by kortschak** [comment] 2017-05-11 06:52
That would be more composable if `HeatMap` took a `palette.ColorMap`. Then the user gets to determine the behaviour of the colour mapping as you describe, but the separation of concerns is maintained (data should not know what colour they are - unless they are a colour).

**Comment by kortschak** [comment] 2017-05-11 06:59
The problem though with using a `palette.ColorMap` is that it needs the `SetMin` and `SetMax` methods, otherwise the user must set the ranges. I don't like these because they have the capacity to give spooky action at a distance.

**Comment by eaburns** [comment] 2017-05-11 14:12
On Wed, May 10, 2017 at 10:11 PM Dan Kortschak <notifications@github.com>
wrote:

> TBH, I think that is telling you something, but what would you propose?
>
> @eaburns <https://github.com/eaburns> Is there any reason not to change
> the Plotter interface to Plot(draw.Canvas, *Plot) error and the signature
> of *Plot.Draw to Draw(c draw.Canvas) error? Here
> <https://github.com/gonum/plot/issues/302#issuecomment-233787482> I wrote
> "Unfortunately errors in plotting are not yet handled without panics (this
> has been discussed before and I believe is an open issue), so that is the
> option if we want to handle this explicitly", but I don't recall where that
> discussion is.
>

I can't remember why there is no error return. My guess is that I was able
to devise a way to avoid error returns for the all plotters that I
initially had in mind and so I convinced myself it wasn't needed.

Feel free to add it if it makes sense now.

**Comment by kortschak** [comment] 2017-05-12 03:28
@btracey @eaburns Please have a look at https://github.com/gonum/plot/tree/errors for a sketch of this (I think errors.go could be expanded to help tracing, but this works as it is).

**Comment by jasonpfox** [comment] 2017-05-14 14:58
An error return really would not be ideal itself, when asking for a plot, you just want the plot (often large set of plots) the best way you can and go from there.  Even if you had errors, I renew my call that heatmap on 0 depth data should not be an error anyway, this is completely legitimate data, especially in one of a large set of heatmaps.  A specific and very simple fix that would resolve this was proposed and rejected because there was an active desire to retain this as an error condition that would crash things (since an error message could not be returned), which I still can not understand....

If you want to consider this an error and check for it, feel free, but you should not complicate heatmaps in general for that or force any more on the caller, just a data set auto-scaled works very well, as long as you gracefuly handle data sets with depth >= 0 vice just depth > 0 ....

**Comment by kortschak** [comment] 2017-05-14 22:50
>A specific and very simple fix that would resolve this was proposed and rejected because there was an active desire to retain this as an error condition that would crash things (since an error message could not be returned), which I still can not understand....

There is "simple" and there is "simple and obviously correct".

To quote Mencken: "For every complex problem there is an answer that is clear, simple, and wrong."

The fact that of three commonly used plotting systems that can produce heat map-like plots, there are three different approaches to handing this issue says to me that there is not a simple obviously correct approach (though note that over the past week I've asked half a dozen colleagues in faculty what they think the appropriate approach to this problem should be and with the exception of one ambivalent response the answer has been to error/panic).

In looking at the code over the week, I may have a solution though - one that needs to be considered in the context of my comments about about simplicity. At the moment, NaN is treated specially (I think icorrectly now - Inf is also treated specially and I don't understand what I was thinking). If there is a `NaN color.Color` field then NaN does not need to be treated in a special hard-coded way, and the NaN that is generated during the color interpolation can be rendered. In this case, a zero Z range would be rendered as a flat field of the NaN color. This is consistent with the mathematics and does not error in the zero range case.

**Comment by jasonpfox** [comment] 2017-05-15 11:38
That sounds like a good solution as long as it does not error / panic.  My
application is generating plots for diagnosis / analysis from
soft-real-time signal processing systems, for 0 depth I don't care much
what color is used as long as the system keeps running smoothly....

--
Jason Fox
-----
jpfox@alumni.rice.edu

**Comment by kortschak** [comment] 2017-05-15 11:47
I intend to keep the panic for min > max, but otherwise it will not panic.

However, I don't understand this requirement that it does not panic or error; from the outset I've shown how to prevent a panic by making a helper to condition the HeatMap and if an error returns, there is an obvious idiom in the branch that I linked above to conditionally ignore plotting errors by type assertion (I still think the errors changes should go in for the general case - though not to fix this problem maybe).

**Closed** 2017-08-03 06:32 UTC
