### ISSUE TITLE
Scatter plot only prints in upper right corner 

### ISSUE THREAD

**Issue by btracey** [gonum/plot#181] opened 2015-03-25 05:38 UTC
Example script:
http://play.golang.org/p/yZRYwjXRCZ

Output:
![orig](https://cloud.githubusercontent.com/assets/3680859/6818950/63ae5f14-d276-11e4-9bab-5383a7863adb.jpg)

**Comment by btracey** [comment] 2015-03-25 05:39
It looks to me like the offset is wrong. It seems like the bottom left corner is starting at the middle of the canvas instead of the bottom left corner.

**Comment by kortschak** [comment] 2015-03-25 05:42
This looks like another rect change error. What canvas type are you using?

**Comment by kortschak** [comment] 2015-03-25 05:46
Would you try that after commenting out https://github.com/gonum/plot/blob/master/vg/vgimg/vgimg.go#L61

**Comment by btracey** [comment] 2015-03-25 05:46
Is ".jpg" a valid answer to that question?

**Comment by kortschak** [comment] 2015-03-25 05:46
Yup.

**Comment by kortschak** [comment] 2015-03-25 05:47
Actualy, you'll need to change the line to (untested) `gc.Translate(0, -h)` I think.

**Comment by btracey** [comment] 2015-03-25 05:49
Bingo on the second one

**Comment by btracey** [comment] 2015-03-25 05:49
Thanks!

**Comment by kortschak** [comment] 2015-03-25 05:53
Would you send a PR for that fix. The test in this case can include a jpeg (or other vgimg format) since this is a test on that package.

**Comment by btracey** [comment] 2015-03-25 05:56
Sure, I'll do that tommorrow. Could you point me to a test whose behavior I can emulate (I haven't been following the plot PRs closely enough)?

**Comment by kortschak** [comment] 2015-03-25 06:01
In this case just make a test in vgimg_test that writes a png/jpg/whatever that is small to a bytes.Buffer and compare it against a Golden value. Use a scatter with a few points. It doesn't need to be fancy. #25 has a test that's fixing the same problem in the general case, but this issue here doesn't need so much work.

**Comment by dgryski** [comment] 2015-03-25 06:31
This is a dupe of https://github.com/gonum/plot/pull/179

**Comment by kortschak** [comment] 2015-03-25 07:08
Well spotted. Thank you.

**Closed** 2015-03-25 07:10 UTC
