### ISSUE TITLE
incorrectly label in pie diagram

### ISSUE THREAD

**Issue by LazarenkoA** [gonum/plot#580] opened 2020-02-17 15:26 UTC
Hi, sometimes the inscription is incorrectly displayed in the diagram, in this example it should be 21, displayed 2

![image](https://user-images.githubusercontent.com/15386101/74666101-f6ce5500-51b1-11ea-84f0-307bd37f60a3.png)

```go
pie.Color = color.RGBA{uint8(rand.Intn(255)), uint8(rand.Intn(255)), uint8(rand.Intn(255)), 255}
pie.Offset.Value = float64(offset)
pie.Total = float64(total)
pie.Labels.Nominal = []string{state}
pie.Labels.Values.Show = true
```

**Comment by sbinet** [comment] 2020-02-17 16:25
thanks for the report.

could you post a minimal reproducer (or a link to the playground) ?
thanks.

**Comment by LazarenkoA** [comment] 2020-02-17 18:58
link to the code.
https://github.com/LazarenkoA/TelegramBot/blob/b756db76935cb71617ae2994868c70b8693586c8/TelegramTasks/GetListUpdateState.go#L304

The problem is also in m, that the bug is repeated not every time, I will try to logging the source data

**Comment by kortschak** [comment] 2020-02-17 21:24
A few questions will help us here.

1. Does this reproduce with other canvas types (svg would be good to test)?
2. Can you a minimal reproducer that does not make use of the  github.com/benoitmasson/plotters/piechart package (debugging through that complicates things)?
3. If you use the [`recorder.Canvas`](https://godoc.org/gonum.org/v1/plot/vg/recorder#Canvas), do you see the expected string for this label?
4. Does this reproduce with non-Cyrillic labels?

**Comment by LazarenkoA** [comment] 2020-02-21 15:19
I managed to repeat the error, it is exactly 0 in two-digit numbers that disappears

```go
file := Buildhart()
fmt.Println(file)


///////////////////////////


func Buildhart() string {
	rand.Seed(time.Now().UnixNano())

	p, err := plot.New()
	if err != nil {
		panic(err)
	}
	p.Legend.Top = true
	p.HideAxes()

	tmpDir, err := ioutil.TempDir("", "")
	if err != nil {
		return ""
	}
	chartFile := filepath.Join(tmpDir, "chart.png")

	offset := 0
	total := 22
	groupState := map[string]int{ "test": 4, "test1": 8, "test2": 10}
	for state, v := range groupState {
		pie, err := piechart.NewPieChart(plotter.Values{float64(v)})
		if err != nil {
			panic(err)
		}
		pie.Color = color.RGBA{uint8(rand.Intn(255)), uint8(rand.Intn(255)), uint8(rand.Intn(255)), 255}
		pie.Offset.Value = float64(offset)
		pie.Total = float64(total)
		pie.Labels.Nominal = []string{state}
		pie.Labels.Values.Show = true
		//pie.Labels.Values.Percentage = true // что бы выводилось в %

		p.Add(pie)
		p.Legend.Add(state, pie)

		offset += v
	}

	if err := p.Save(500, 500, chartFile); err != nil {
		return ""
	} else {
		return chartFile
	}

}
```

**Comment by sbinet** [comment] 2020-02-21 16:11
AFAICT, it's a bug in `piechart` proper, not in `gonum/plot`.

this line:
https://github.com/benoitmasson/plotters/blob/52aac251d99bec3d9b2794e2fd736934a485ec63/piechart/piechart.go#L195

will transform the string `"10.00"` into `"1"`.

a possible fix could be to use `'g'` instead of `'f'` (and drop the `strings.TrimRight`).

also, `benoitmasson/plotter` is still importing `gonum/plot` from `"github.com/gonum/plot"` so... perhaps the occasion to send a PR with your fix and that import path change (otherwise, it's bound to fail when Go-modules will be the only game in town...)

closing as the issue isn't in `gonum/plot`.
(feel free to re-open if you feel there's something to be done on our end.)

**Closed by sbinet** 2020-02-21 16:11 UTC
