### ISSUE TITLE
`go get gonum.org/v1/gonum` returns 404

### ISSUE THREAD

**Issue by niamster** [gonum/plot#629] opened 2020-06-20 16:56 UTC
### What are you trying to do?
Install `gonum`

### What did you do?

```
go get -d -v gonum.org/v1/gonum
unrecognized import path "gonum.org/v1/gonum": reading https://gonum.org/v1/gonum?go-get=1: 404 Not Found
```

### What did you expect to happen?

Package to be downloaded.

### What actually happened?

`https://www.gonum.org/v1/gonum/` serves `404`

### What version of Go and Gonum/plot are you using?

Latest

### Does this issue reproduce with the current master?
Any version.

**Comment by kortschak** [comment] 2020-06-20 21:56
Duplicate of gonum/website#9.

**Closed by kortschak** 2020-06-20 21:56 UTC
