### ISSUE TITLE
vg/vgimg: fails to draw horizontal lines with many line segments

### ISSUE THREAD

**Issue by kortschak** [gonum/plot#687] opened 2021-04-21 00:17 UTC
### What are you trying to do?

Plot a long data series.

### What did you do?

This won't run in playground due to timeout, but change the playground constant to false and it will run locally.

https://play.golang.org/p/gSINhzskCHi

### What did you expect to happen?

Plot something equivalent to this (svg output).
![Screenshot from 2021-04-21 09-24-46](https://user-images.githubusercontent.com/275221/115477711-b1108f00-a283-11eb-97a2-935e0b4d078f.png)

### What actually happened?

![bug](https://user-images.githubusercontent.com/275221/115477736-bcfc5100-a283-11eb-9e9b-c5177b6c3a7a.png)

The plot is correct with svg, eps and pdf formats, but missing the horizontal segment with png, tiff and jpg, so it appears to be due to vg/vgimg. The `*Canvas.Stroke` method is a thin wrapper around `*"github.com/fogleman/gg".Context.Stroke`, so the error may there. Note also that the effect is not noticeably visible for `len(data)` values lower than ~4000 in the bug.go reproducer.

### What version of Go and Gonum/plot are you using?

v0.9.0 caab7788e04dfd7a74cec4ee80f55b7d1f9a2bfa

### Does this issue reproduce with the current master?

Yes.

**Comment by sbinet** [comment] 2021-04-21 15:50
probably a duplicate of:
- https://github.com/gonum/plot/issues/645
- https://github.com/gonum/plot/issues/559

**Comment by kortschak** [comment] 2021-04-21 21:16
Possibly #645, but I don't think it looks like #559.

**Comment by FP-Guitar** [comment] 2021-09-28 12:56
Ran into a similar issue than this. Followed the "Duplicate" issue and can reproduce the behaviour:
"Works with pdf and svg backend, fails with tiff"

**Comment by sbinet** [comment] 2021-09-28 13:10
then this is an issue with the underlying `gg` package we use for the `vgimg` backend:

- https://github.com/fogleman/gg/issues/85

I must admit I haven't followed up and didn't dive in `freetype/raster`...
did you try using `vg/vggio` in headless mode?
as hinted [there](https://github.com/gonum/plot/issues/559#issuecomment-749221261) `vg/vggio` may give slightly better results.

**Comment by sbinet** [comment] 2021-11-25 10:58
well... as mentioned in https://github.com/fogleman/gg/issues/85#issuecomment-955007266 it's been a while.
I'll probably bite the bullet and fork (where? `sbinet-gonum/gg`? `gonum/plot-vgimg-gg`?) `gg` to fix this issue.
any suggestions/preferences as to where this should live?

**Comment by kortschak** [comment] 2021-11-25 20:14
I don't think I can answer that because the choice is essentially an indication of where the burden will lie and that's obviously a thing for you to decide. I can say that I will try to help maintain it no matter where it lives.

**Closed** 2022-01-19 10:01 UTC
